apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: pi-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      hostNetwork: true
      containers:
      - name: cloudflare-ddns
        image: favonia/cloudflare-ddns:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-secret
              key: CF_API_TOKEN
        - name: DOMAINS
          valueFrom:
            configMapKeyRef:
              name: cloudflare-config
              key: domain
        - name: IP4_PROVIDER
          value: "cloudflare.trace"
        - name: IP6_PROVIDER
          value: "none"
        - name: PROXIED
          value: "false"
        - name: UPDATE_CRON
          value: "@daily"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: "1"
            memory: 512Mi
