apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-avahi-cname
  namespace: pi-services
  labels:
    app: go-avahi-cname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-avahi-cname
  template:
    metadata:
      labels:
        app: go-avahi-cname
    spec:
      hostNetwork: true
      containers:
      - name: go-avahi-cname
        image: ghcr.io/bjw-s/go-avahi-cname:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: dbus
          mountPath: /var/run/dbus
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: "1"
            memory: 128Mi
      volumes:
      - name: dbus
        hostPath:
          path: /var/run/dbus
          type: Directory
