apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: pi-services
  labels:
    app: matter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      containers:
      - name: matter-server
        image: ghcr.io/home-assistant-libs/python-matter-server:stable
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5580
          hostPort: 5580
        volumeMounts:
        - name: data
          mountPath: /data
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: data
        hostPath:
          path: /kubernetes-volumes/matter-server
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: pi-services
spec:
  type: ClusterIP
  ports:
  - port: 5580
    targetPort: 5580
  selector:
    app: matter-server
